### ISSUE TITLE
spring-boot-camel (change context-path)

### ISSUE THREAD

**Issue by iteaky** [eugenp/tutorials#11160]
```
        <camel.version>3.10.0</camel.version>

   <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-spring-boot-starter</artifactId>
            <version>${camel.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-servlet-starter</artifactId>
            <version>${camel.version}</version>
        </dependency>
```

application.yaml
```

camel:
  component:
    servlet:
      mapping:
        contextPath: /cameltest/*
```

There is no such field (mapping.contextpath) in class ServletComponentConfiguration.java

How could I change /camel root path?
